USE COMPANY;
-- PROJECT TABLE :
CREATE TABLE PROJECT(PROJECT_ID INT PRIMARY KEY, PROJECT_NAME VARCHAR(100), STATUS VARCHAR(20) DEFAULT'PENDING');

INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, STATUS) VALUES
(1 , 'HTML & CSS' , 'HALF');

SELECT * FROM PROJECT;

-- EMPLOYEES TABLE :
CREATE TABLE EMPL1(EMP_ID INT PRIMARY KEY , NAME VARCHAR(20) NOT NULL, DEPARTMENT VARCHAR(20) DEFAULT'SALES', SALARY INT , DATE DATE);

SELECT * FROM EMPL1;

DESC EMPL1;

-- MODIFY :
ALTER TABLE EMPL1 MODIFY SALARY DECIMAL(10,2);

-- LOGICAL OPERATOR :
SELECT DEPARTMENT , EMP_ID, NAME FROM EMPL1 WHERE DEPARTMENT='HR' OR DEPARTMENT='SALES';
SELECT DEPARTMENT , EMP_ID , NAME FROM EMPL1 WHERE DEPARTMENT='HR' AND DATE=28/11/2025;
SELECT *FROM EMPL1 WHERE DEPARTMENT IN('HR' , 'SALES');

-- SUM :
SELECT DEPARTMENT, SUM(SALARY) FROM EMPL1 GROUP BY DEPARTMENT;

-- MAX AND MIN :
SELECT DEPARTMENT , MAX(SALARY) , MIN(SALARY) FROM EMPL1 GROUP BY DEPARTMENT;

-- AVG SALARY :
SELECT DEPARTMENT , AVG(SALARY) FROM EMPL1 GROUP BY DEPARTMENT ORDER BY AVG(SALARY) DESC;

-- COUNT :
SELECT DEPARTMENT , COUNT(EMP_ID) FROM EMP1 GROUP BY DEPARTMENT;
SELECT DEPARTMENT , SALARY, COUNT(EMP_ID), AVG(SALARY) FROM EMPL1 GROUP BY DEPARTMENT HAVING AVG(SALARY)>SALARY;

-- 2ND HIGHEST SALARY :
SELECT * FROM EMPL1 ORDER BY SALARY DESC LIMIT 1 OFFSET 1;

-- UPDATING HR SALARY :
SET SQL_SAFE_UPDATES=0;
UPDATE EMPL1 SET SALARY=70000 WHERE DEPARTMENT='HR';
UPDATE EMPL1 SET DEPARTMENT='HR' WHERE EMP_ID=101;

-- ADDING NEW COLUMN :
ALTER TABLE EMPL1 ADD PHONE_NUMBER INT;

-- RENAME COLUMN :
ALTER TABLE EMPL1 RENAME COLUMN PHONE_NUMBER TO CONTACT_NUMBER;

-- DROP COLUMN :
ALTER TABLE EMPL1 DROP COLUMN CONTACT_NUMBER;