CREATE DATABASE GOOGLE;
SHOW DATABASES;

USE GOOGLE;

CREATE TABLE EMP (EMP_ID INT PRIMARY KEY, EMP_NAME VARCHAR(50) NOT NULL , SALARY DECIMAL(10 , 2) CHECK(SALARY>10000), DEPARTMENT VARCHAR(50) DEFAULT'IT');

INSERT INTO EMP (EMP_ID , EMP_NAME , SALARY) VALUES
(101,'SHIVANI',90000.50) ;

SELECT * FROM EMP;

DESC EMP;
-- TO ADD COLUMN
ALTER TABLE EMP ADD COLUMN CITY VARCHAR(20);
-- MODIFY THE DATA TYPE
ALTER TABLE EMP MODIFY SALARY INT;
-- RENAME THE COLUMN 
ALTER TABLE EMP RENAME COLUMN DEPARTMENT TO DEPART;
-- DROP COLUMN 
ALTER TABLE EMP DROP CITY;
