CREATE DATABASE COMPANY;
SHOW DATABASES;

USE COMPANY;

CREATE TABLE EMPLOYEE (EMP_ID INT PRIMARY KEY, EMP_NAME VARCHAR(50) , DEPARTMENT VARCHAR (20) , SALARY INT , CITY VARCHAR(20));

INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT , SALARY , CITY) VALUES
(101 , 'Rahul Mehta' , 'HR' , 55000	, 'Mumbai');

INSERT INTO EMPLOYEE (EMP_ID , EMP_NAME , DEPARTMENT , SALARY , CITY) VALUES
(102 , 'SNEHA PATEL' , 'IT' , 75000 , 'PUNE') , 
(103 , 'AMIT SHARMA' , 'FINANCE' , 62000 , 'DELHI') ,
(104 , 'NEHA SINGH' , 'IT' , 82000 , 'MUMBAI') ,
(105 , 'RAJAT VERMA' , 'HR' , 50000 , 'CHENNAI') ,
(106 , 'POOJA DAS' , 'FINANCE' , 72000 , 'PUNE') ,
(107 , 'KARAN GUPTA' , 'IT' , 88000 , 'DELHI') ,
(108 , 'DEEPA JOSHI' , 'MARKETING' , 61000 , 'MUMBAI') ,
(109 , 'RAVI KUMAR' , 'HR' , 56000 , 'DELHI') ,
(110 , 'NISHA REDDY' , 'IT' , 70000 , 'HYDERABAD');

SELECT * FROM SHIVANI;

SELECT EMP_NAME, DEPARTMENT, SALARY FROM EMPLOYEE;
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPARTMENT='IT';
SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE SALARY>70000;
SELECT EMP_NAME,SALARY,CITY FROM EMPLOYEE WHERE CITY='MUMBAI' OR CITY='DELHI';
SELECT EMP_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY ;
SELECT EMP_NAME , SALARY FROM EMPLOYEE ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEE WHERE DEPARTMENT = 'FINANCE' ORDER BY EMP_NAME;
SELECT * FROM EMPLOYEE ORDER BY DEPARTMENT, SALARY DESC;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 5;
SELECT count(DEPARTMENT), DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 3;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 3 OFFSET 3;
SELECT EMP_NAME FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 2 OFFSET 1;
SELECT DEPARTMENT, MAX(SALARY), MIN(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT COUNT(CITY), CITY FROM EMPLOYEE GROUP BY CITY;
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPARTMENT='IT' LIMIT 5;
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY count(EMP_NAME) DESC;
SELECT DEPARTMENT , AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT HAVING AVG(SALARY)>60000;
SELECT EMP_NAME,SALARY FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 2 OFFSET 1;
SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY SUM(SALARY) DESC;
SELECT DEPARTMENT,COUNT(DEPARTMENT) FROM EMPLOYEE GROUP BY DEPARTMENT HAVING AVG(SALARY)>50000;
SELECT DEPARTMENT, COUNT(SALARY) SALARY FROM EMPLOYEE GROUP BY DEPARTMENT HAVING AVG (SALARY)>50000;
SELECT COUNT(EMP_NAME),DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT='IT' OR DEPARTMENT='HR' GROUP BY DEPARTMENT;
SELECT EMP_NAME,DEPARTMENT FROM EMPLOYEE WHERE  CITY ='MUMBAI' AND DEPARTMENT='HR';
SELECT * FROM EMPLOYEE WHERE DEPARTMENT='HR' OR DEPARTMENT='IT';
SELECT * FROM EMPLOYEE WHERE DEPARTMENT ='IT';
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPARTMENT='IT' AND CITY='MUMBAI';
SELECT EMP_NAME,DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT='HR' OR DEPARTMENT='FINANCE';
SELECT EMP_NAME, DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT IN('HR','FINANCE');
SELECT EMP_NAME,DEPARTMENT FROM EMPLOYEE WHERE CITY IN('MUMBAI' , 'PUNE' , 'DELHI');
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;
SELECT DEPARTMENT, AVG(SALARY)FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(EMP_NAME) FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 2;
ALTER TABLE EMPLOYEE ADD CREDIT_DATE DATE;

SELECT * FROM EMPLOYEE;

SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-05' WHERE EMP_ID=101;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-06' WHERE EMP_ID=102;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-07' WHERE EMP_ID=103;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-08' WHERE EMP_ID=104;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-09' WHERE EMP_ID=105;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-28' WHERE EMP_ID=106;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-31' WHERE EMP_ID=107;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-14' WHERE EMP_ID=108;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-03' WHERE EMP_ID=109;
UPDATE EMPLOYEE SET CREDIT_DATE='2025-01-18' WHERE EMP_ID=110;

UPDATE EMPLOYEE SET EMP_NAME='SHIVANI' WHERE EMP_ID='101';
UPDATE EMPLOYEE SET SALARY=SALARY+50000 WHERE DEPARTMENT='HR';
UPDATE EMPLOYEE SET SALARY=SALARY*0.25;
UPDATE EMPLOYEE SET SALARY=60000 WHERE EMP_ID='101';
UPDATE EMPLOYEE SET SALARY=SALARY*0.5 WHERE EMP_ID='101';
UPDATE EMPLOYEE SET SALARY=SALARY*1.5 WHERE EMP_ID='101';

SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 1;
SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY SUM(SALARY)DESC LIMIT 1 OFFSET 2;
SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEE  SET SALARY = 50000 WHERE DEPARTMENT = 'HR';
UPDATE EMPLOYEE SET SALARY = 70000 WHERE DEPARTMENT = 'FINANCE';
UPDATE EMPLOYEE SET SALARY = 80000 WHERE DEPARTMENT = 'MARKETING';
UPDATE EMPLOYEE SET SALARY = 60000 WHERE DEPARTMENT = 'IT'; 
SELECT * FROM EMPLOYEE;
SELECT SALARY * 1.25 FROM EMPLOYEE; 
