USE COMPANY;

CREATE TABLE EMP1 (EMP_ID INT PRIMARY KEY, EMP_NAME VARCHAR(50) , DEPARTMENT VARCHAR (20) , SALARY INT , CITY VARCHAR(20));

INSERT INTO EMP1 (EMP_ID , EMP_NAME , DEPARTMENT , SALARY , CITY) VALUES
(101 , 'Rahul Mehta' , 'HR' , 55000	, 'Mumbai');

INSERT INTO EMP1 (EMP_ID , EMP_NAME , DEPARTMENT , SALARY , CITY) VALUES
(102 , 'SNEHA PATEL' , 'IT' , 75000 , 'PUNE') , 
(103 , 'AMIT SHARMA' , 'FINANCE' , 62000 , 'DELHI') ,
(104 , 'NEHA SINGH' , 'IT' , 82000 , 'MUMBAI') ,
(105 , 'RAJAT VERMA' , 'HR' , 50000 , 'CHENNAI') ,
(106 , 'POOJA DAS' , 'FINANCE' , 72000 , 'PUNE') ,
(107 , 'KARAN GUPTA' , 'IT' , 88000 , 'DELHI') ,
(108 , 'DEEPA JOSHI' , 'MARKETING' , 61000 , 'MUMBAI') ,
(109 , 'RAVI KUMAR' , 'HR' , 56000 , 'DELHI') ,
(110 , 'NISHA REDDY' , 'IT' , 70000 , 'HYDERABAD');

SELECT * FROM SHIVANI;

-- MAX AND MIN :
SELECT DEPARTMENT, MIN(SALARY), MAX(SALARY) FROM SHIVANI GROUP BY DEPARTMENT;
-- 2ND HIGHEST SALARY :
SELECT EMP_NAME, SALARY FROM SHIVANI ORDER BY SALARY DESC LIMIT 1 OFFSET 1;
-- SALARY BTW 50000 TO 70000 :
SELECT EMP_NAME, SALARY FROM SHIVANI WHERE SALARY BETWEEN 50000 AND 70000;
-- DEPARTMENT COUNT :
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM SHIVANI GROUP BY DEPARTMENT ORDER BY COUNT(EMP_NAME) DESC;
-- CITY='MUMBAI' OR SALARY>60000 :
SELECT EMP_NAME FROM SHIVANI WHERE CITY='MUMBAI' OR SALARY>60000;
 