USE COMPANY;
SHOW TABLES;

SELECT * FROM SHIVANI_SINGH;
SELECT EMP_NAME,DEPARTMENT FROM SHIVANI_SINGH;
SELECT EMP_NAME,DEPARTMENT FROM SHIVANI_SINGH WHERE DEPARTMENT='IT';
SELECT * FROM SHIVANI_SINGH WHERE SALARY>70000;
SELECT * FROM SHIVANI_SINGH WHERE CITY='DELHI' OR CITY='MUMBAI';
SELECT * FROM SHIVANI_SINGH WHERE DEPARTMENT='FINANCE'AND SALARY>80000;
SELECT * FROM SHIVANI_SINGH WHERE CITY='BANGALORE' OR CITY='DELHI';
SELECT * FROM SHIVANI_SINGH WHERE DEPARTMENT='IT' AND CITY='MUMBAI';
SELECT * FROM SHIVANI_SINGH WHERE JOINING_DATE=2021-01-01 AND SALARY<80000; 
SELECT DEPARTMENT, SUM(SALARY) SALARY FROM SHIVANI_SINGH GROUP BY DEPARTMENT;
SELECT DEPARTMENT, AVG(SALARY) SALARY FROM SHIVANI_SINGH GROUP BY DEPARTMENT;
SELECT COUNT(EMP_NAME), DEPARTMENT FROM SHIVANI_SINGH GROUP BY DEPARTMENT ORDER BY DEPARTMENT; 
SELECT * FROM SHIVANI_SINGH ORDER BY SALARY DESC;
SELECT * FROM SHIVANI_SINGH ORDER BY DEPARTMENT, SALARY ASC;
ALTER TABLE SHIVANI_SINGH ADD COLUMN EMAIL VARCHAR(100);
SET SQL_SAFE_UPDATES=0;
UPDATE SHIVANI_SINGH SET SALARY=75000 WHERE EMP_ID=108;
SELECT * FROM SHIVANI_SINGH;
ALTER TABLE SHIVANI_SINGH DROP COLUMN CITY;


