CREATE DATABASE MS;
SHOW DATABASES;

USE MS;

CREATE TABLE STUDENT(ID INT PRIMARY KEY, NAME VARCHAR(50) , COURSE VARCHAR(20) , LOCATION VARCHAR(50));

INSERT INTO STUDENT (ID , NAME , COURSE , LOCATION) VALUES
(1 , 'SHIVANI', 'CYBER SECURITY' , 'BHOPAL');

INSERT INTO STUDENT (ID , NAME , COURSE , LOCATION) VALUES
(2 , 'SHREYA' , 'PYTHON' , 'INDORE') ,
(3 , 'DARAKSHA' , 'AI' , 'GWALIOR') ,
(4 , 'ARSHI' , 'FULLSTACK' , 'CHINDWARA') ,
(5 , 'SHWETA' , 'ML' , 'BETUL') , 
(6 , 'POONAM' , 'CYBER SECURITY' , 'INDORE') , 
(7 , 'VIJAY' , 'AI' , 'BHOPAL') ,
(8 , 'SHIVAM' , 'PYTHON' , 'GWALIOR') ,
(9 , 'RIYA' , 'FULLSTACK' , 'BETUL') , 
(10 , 'PRIYANSHI' , 'ML' , 'CHINDWARA');

SELECT * FROM STUDENT;
SELECT count(NAME) , COURSE FROM STUDENT WHERE COURSE='PYTHON';
SELECT count(LOCATION) , COURSE FROM STUDENT WHERE COURSE='FULLSTACK';
SELECT NAME FROM STUDENT WHERE COURSE='CYBER SECURITY';

DROP DATABASE CYBROM;
SHOW TABLES;

