USE COMPANY;

CREATE TABLE STUDENT (STUDENT_ID INT PRIMARY KEY , STUDENT_NAME VARCHAR (20) , CLASS INT);

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME , CLASS) VALUES
(1 , 'RIYA' , 10) , (2, 'AMAN' , 9) , (3 , 'SNEHA' , 10) ;

SELECT * FROM STUDENT;

CREATE TABLE FEES (FEE_ID INT , STUDENT_ID INT , AMOUNT DECIMAL(5,2) , FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT (STUDENT_ID));

SELECT * FROM FEES;
desc fees;

INSERT INTO FEES1 (FEE_ID , STUDENT_ID , AMOUNT) VALUES
(101, 1, 50000.18) , (102, 2, 45000.13) , (103, 3, 30000.12);
INSERT INTO FEES (FEE_ID , STUDENT_ID , AMOUNT) VALUES
(104, 1, 500.11) , (105, 2, 450.11) , (106, 3, 300.11);

CREATE TABLE FEES1 (FEE_ID INT , STUDENT_ID INT , AMOUNT DECIMAL(7,2) , FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT (STUDENT_ID));

SELECT * FROM FEES1;