show databases;
creATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEE( ID INT, NAME VARCHAR(20), DEPARTMENT VARCHAR (20), LOCATION VARCHAR (20), SALARY INT );

INSERT INTO EMPLOYEE ( ID, NAME, DEPARTMENT,LOCATION, SALARY) VALUES
( 101,'SHWETA','HR','INDORE',100000),
(102,'SHIVANI','IT','BHOPAL',90000),
(103,'DARAKSHA','SALES','BHOPAL',80000);

INSERT INTO EMPLOYEE ( ID, NAME, DEPARTMENT,LOCATION, SALARY) VALUES
(104,'ARSHI','MARKETING','CHINDWARA',70000),
(105,'SHREYA', 'HR', 'BHOPAL','100000'),
(106,'POONAM', 'IT', 'SEHORE','90000'),
(107,'VIJAY','SALES','JABALPUR','80000'),
(108,'ADITYA', 'MARKETING', 'JABALPUR','70000'),
(109,'PRIYANSHI','ITI', 'GWALIOR','60000'),
(110,'SUHANI','ITI','GWALIOR','60000');

SELECT*FROM EMPLOYEE;
SELECT NAME FROM EMPLOYEE WHERE DEPARTMENT='IT' AND SALARY<90000;
SELECT * FROM EMPLOYEE WHERE DEPARTMENT!='HR';
SELECT * FROM EMPLOYEE WHERE NOT DEPARTMENT='HR';
SELECT NAME,SALARY FROM EMPLOYEE WHERE SALARY>=50000 AND SALARY<=80000;
SELECT NAME,SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 50000 AND 80000;
SELECT NAME, SALARY FROM EMPLOYEE WHERE SALARY>=50000 OR SALARY<=80000;
SELECT NAME, SALARY FROM EMPLOYEE ORDER BY SALARY DESC;
SELECT *FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 2;
SELECT * FROM EMPLOYEE ORDER BY SALARY LIMIT 1 OFFSET 2;
SELECT DEPARTMENT,sum(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT,sum(SALARY) FROM EMPLOYEE  GROUP BY DEPARTMENT ORDER BY sum(SALARY) DESC LIMIT 1 OFFSET 1;
SELECT DEPARTMENT,sum(SALARY) FROM EMPLOYEE  GROUP BY DEPARTMENT ORDER BY sum(SALARY) DESC LIMIT 2;
SELECT DEPARTMENT,sum(SALARY) FROM EMPLOYEE  GROUP BY DEPARTMENT ORDER BY sum(SALARY) DESC LIMIT 1 OFFSET 2;
SELECT NAME, SALARY,DEPARTMENT FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1;