USE STUDENT;

CREATE TABLE STUDENTS(STUDENT_ID INT PRIMARY KEY , STUDENT_NAME VARCHAR (30) , CLASS INT);

INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, CLASS) VALUES
(1, 'RIYA', 10), (2, 'AMAN' , 9) , (3, 'SNEHA' , 8);

SELECT * FROM STUDENTS;

CREATE TABLE MARKS(MARKS_ID INT, STUDENT_ID INT ,FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID), SUBJECT VARCHAR(20), MARKS INT);

INSERT INTO MARKS (MARKS_ID , STUDENT_ID , SUBJECT , MARKS) VALUES
(1, 1, 'MATHS' , 90) , (2 , 1 , 'SCIENCE' , 88) , (3, 2,'MATHS' ,78);

SELECT * FROM MARKS;

-- INNER JOINTS :
SELECT S.STUDENT_NAME, M.SUBJECT, M.MARKS
FROM STUDENTS AS S
INNER JOIN MARKS AS M
ON S.STUDENT_ID = M.STUDENT_ID;

-- LEFT JOINTS :
SELECT S.STUDENT_NAME, M.SUBJECT, M.MARKS
FROM STUDENTS AS S
LEFT JOIN MARKS AS M
ON S.STUDENT_ID = M.STUDENT_ID;

-- RIGHT JOINTS :
SELECT S.STUDENT_NAME, M.SUBJECT, M.MARKS
FROM STUDENTS AS S
RIGHT JOIN MARKS AS M
ON S.STUDENT_ID = M.STUDENT_ID;

-- UNION :
SELECT * FROM STUDENTS S
LEFT JOIN MARKS AS M
ON S.STUDENT_ID = M.STUDENT_ID;

UNION

SELECT * FROM STUDENTS AS S
RIGHT JOIN MARKS AS M
ON S.STUDENT_ID = M.STUDENT_ID;

SELECT * FROM MARKS WHERE MARKS>80;

